<a href="https://colab.research.google.com/github/mohammedibrahim0o05/-Detecting-steganography-with-tools-like-StegExpose-analyzing-file-signatures/blob/main/introduction%20to%20kaggle%20and%20data%20preprocessing%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Dummy data to avoid FileNotFoundError
csv_data = """RowNumber,Surname,Geography,Gender,CreditScore,Exited
1,Hargrave,France,Female,619,1
2,France,Female,608,0
3,Germany,Male,502,1
4,Spain,Female,699,0
5,France,Male,850,0
"""
df = pd.read_csv(io.StringIO(csv_data), index_col="RowNumber")
df.head()

            Surname Geography  Gender  CreditScore  Exited
RowNumber
1          Hargrave    France  Female          619     1.0
2            France    Female     608            0     NaN
3           Germany      Male     502            1     NaN
4             Spain    Female     699            0     NaN
5            France      Male     850            0     NaN

In [3]:
df.isnull().sum()

Surname        0
Geography      0
Gender         0
CreditScore    0
Exited         4
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df=df.drop(['Surname', 'Geography','Gender'], axis=1)
scaler=StandardScaler()
df=pd.DataFrame(scaler.fit_transform(df))
df.head()

          0    1
0  1.999998  0.0
1 -0.501009  NaN
2 -0.496969  NaN
3 -0.501009  NaN
4 -0.501009  NaN

In [6]:
X,Y=df.iloc[:,:-1].values ,df.iloc[:,-1].values
print('Input:\n',X,'\nOutput:\n',Y)
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X, Y, test_size=0.2)
print("Xtrain:\n" ,Xtrain, "\nXtest:\n", Xtest)
print("\nYtrain:\n" ,Ytrain, "\nYtest:\n", Ytest)

Input:
 [[ 1.99999755]
 [-0.50100949]
 [-0.49696909]
 [-0.50100949]
 [-0.50100949]]
Output:
 [ 0. nan nan nan nan]
Xtrain:
 [[-0.50100949]
 [-0.50100949]
 [-0.50100949]
 [ 1.99999755]]
Xtest:
 [[-0.49696909]]

Ytrain:
 [nan nan nan  0.]
Ytest:
 [nan]